spring.application.name=ms-archivos

server.port=8086

minio.url=http://localhost:9000
minio.access-key=admin
minio.secret-key=admin123
minio.bucket=mascotas

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
