spring.application.name=ms-archivos

server.port=8086

minio.url=${MINIO_URL:http://localhost:9000}
minio.access-key=${MINIO_ACCESS_KEY:admin}
minio.secret-key=${MINIO_SECRET_KEY:admin123}
minio.bucket=${MINIO_BUCKET:mascotas}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
