CREATE SCHEMA IF NOT EXISTS auth;
CREATE SCHEMA IF NOT EXISTS mascotas;
CREATE SCHEMA IF NOT EXISTS geolocalizacion;
CREATE SCHEMA IF NOT EXISTS matching;
CREATE SCHEMA IF NOT EXISTS notificaciones;
CREATE SCHEMA IF NOT EXISTS archivos;
CREATE SCHEMA IF NOT EXISTS auditoria;
