spring.application.name=ms-auditoria

server.port=8087

spring.datasource.url=jdbc:postgresql://localhost:5432/sanosysalvos
spring.datasource.username=admin
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=auditoria
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin123

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
